### ISSUE TITLE
CornerNet pretrained weights

### ISSUE THREAD

**Issue by keravraj20** [zzzxxxttt/pytorch_simple_centernet_45#27]
I was not able to download "checkpoint.t7" from your referred path?
Could you provide me checkpoint.t7 file? since I'm from overseas I can't create account in "https://pan.baidu.com/s/1tp9-5CAGwsX3VUSdV276Fg" ?

**Comment by zzzxxxttt** [comment]
try [this](https://github.com/zzzxxxttt/pytorch_simple_CenterNet_45/releases/download/v1.0/checkpoint.t7)

**Comment by keravraj20** [comment]
Thank you @zzzxxxttt for replying...While running train.py in "single GPU or multi GPU using nn.DataParallel", I'm getting this error. Can you pls tell me wat is the pblm?

I get this error:
unable to import tensorboardX, log will be recorded by pytorch!

Namespace(arch='large_hourglass', batch_size=48, ckpt_dir='./ckpt/coco_hg_512_dp', data_dir='./data', dataset='coco', dist=False, img_size=512, local_rank=0, log_dir='./logs/coco_hg_512_dp', log_interval=100, log_name='coco_hg_512_dp', lr=0.0005, lr_step=[90, 120], num_epochs=140, num_workers=10, pretrain_dir='./ckpt/pretrain/checkpoint.t7', pretrain_name='pretrain', root_dir='./', split_ratio=1.0, test_topk=100, val_interval=5) [2020-10-04 07:23:14,255]
Setting up data... [2020-10-04 07:23:14,256]
==> initializing coco 2017 train data.
loading annotations into memory...
Traceback (most recent call last):
  File "train.py", line 237, in <module>
    main()
  File "train.py", line 92, in main
    train_dataset = Dataset(cfg.data_dir, 'train', split_ratio=cfg.split_ratio, img_size=cfg.img_size)
  File "/content/drive/My Drive/pytorch_cn/datasets/coco.py", line 77, in __init__
    self.coco = coco.COCO(self.annot_path)
  File "/root/.local/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 54525953 (char 54525952)

**Comment by zzzxxxttt** [comment]
Never met this before, I guess there is something wrong with your dataset, maybe the annotation does not follow the coco format.

**Comment by ianwang35** [comment]
@zzzxxxttt 
作者您好，请问只需要把checkpoint丢到对应的位置就好吗?因为我自己实作resdcn可以成功，但是用这个large hourglass的pretrained他就会有no param的情况生。如果方便的话请您给我一个操作方式，谢谢

**Comment by manchr180** [comment]
Can you give links for resnet18 VOC as well?
